version: 2.1

orbs:
  orb-tools: circleci/orb-tools@11.6.1
  shellcheck: circleci/shellcheck@3.4

filters: &filters
  tags:
    only: /.+/

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/review:
          filters: *filters
      - shellcheck/check:
          filters: *filters