description: >
  This is a sample executor using Docker and Python.

docker:
  - image: 'cimg/python:<<parameters.tag>>'
resource_class: << parameters.resource_class >>

parameters:
  tag:
    type: string
    default: "3.8"
    description: >
      Pick a specific circleci/python image variant:
      https://hub.docker.com/r/cimg/python/tags
  resource_class:
    description: Specify the resource class for Docker Executor
    type: string
    default: "small"