description: Executor for path-filtering orb

docker:
  - image: 'cimg/python:<<parameters.tag>>'

parameters:
  tag:
    type: string
    default: "3.12"
    description: >
      Pick a specific cimg/python image variant:
      https://hub.docker.com/r/cimg/python/tags
