description: >
  This is a sample executor using Docker

docker:
  - image: 'cimg/base:<<parameters.tag>>'

parameters:
  tag:
    type: string
    default: "current-22.04"
    description: >
      Pick a specific cimg/base image variant:
      https://hub.docker.com/r/cimg/base/tags
